name: CI (back-end)

# Back-end build (conditional)
#  Ensures the back-end builds and tests.
#  Should only fire if there are changes to the `/src/` directory where the Java code lives.
on:
  push:
    branches: [ master, dev ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'src/**'
  workflow_dispatch:
jobs:
  front_end_build:
    name: 'Back-end build'
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@v3.4.0

      - uses: actions/checkout@v2

      - name: Cache mvn dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '15'

      - name: Run back-end build
        env:
          npm_config_audit: false
        run: mvn -B package --file pom.xml
