name: Front-end Checks

on:
  push:
    paths:
      - './HTTP/**'
    branches: [ master, dev ]
  pull_request:
    paths:
      - './HTTP/**'
    branches: [ master, dev ]
  workflow_dispatch:

defaults:
  run:
    working-directory: './HTTP/'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x
          cache: 'npm'

      - name: Prepare
        run: npm ci

      - name: Typecheck
        run: npm run check-types

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
